//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StaticDotNet.ParameterValidation.Resources {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///    A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ExceptionMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        internal ExceptionMessages() {
        }
        
        /// <summary>
        ///    Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("StaticDotNet.ParameterValidation.Resources.ExceptionMessages", typeof(ExceptionMessages).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///    Overrides the current thread's CurrentUICulture property for all
        ///    resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Value cannot be empty..
        /// </summary>
        public static string VALUE_CANNOT_BE_EMPTY {
            get {
                return ResourceManager.GetString("VALUE_CANNOT_BE_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Value cannot be empty or white space..
        /// </summary>
        public static string VALUE_CANNOT_BE_EMPTY_OR_WHITE_SPACE {
            get {
                return ResourceManager.GetString("VALUE_CANNOT_BE_EMPTY_OR_WHITE_SPACE", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Value cannot be null..
        /// </summary>
        public static string VALUE_CANNOT_BE_NULL {
            get {
                return ResourceManager.GetString("VALUE_CANNOT_BE_NULL", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Value cannot be null, empty or white space..
        /// </summary>
        public static string VALUE_CANNOT_BE_NULL_EMPTY_OR_WHITE_SPACE {
            get {
                return ResourceManager.GetString("VALUE_CANNOT_BE_NULL_EMPTY_OR_WHITE_SPACE", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Value cannot be null or empty..
        /// </summary>
        public static string VALUE_CANNOT_BE_NULL_OR_EMPTY {
            get {
                return ResourceManager.GetString("VALUE_CANNOT_BE_NULL_OR_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Value must be a class..
        /// </summary>
        public static string VALUE_MUST_BE_A_CLASS {
            get {
                return ResourceManager.GetString("VALUE_MUST_BE_A_CLASS", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Value must be an interface..
        /// </summary>
        public static string VALUE_MUST_BE_AN_INTERFACE {
            get {
                return ResourceManager.GetString("VALUE_MUST_BE_AN_INTERFACE", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Value must be assignable to &apos;{0}&apos;..
        /// </summary>
        public static string VALUE_MUST_BE_ASSIGNABLE_TO {
            get {
                return ResourceManager.GetString("VALUE_MUST_BE_ASSIGNABLE_TO", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Value must be between &apos;{0}&apos; and &apos;{1}&apos;..
        /// </summary>
        public static string VALUE_MUST_BE_BETWEEN {
            get {
                return ResourceManager.GetString("VALUE_MUST_BE_BETWEEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Value must be empty..
        /// </summary>
        public static string VALUE_MUST_BE_EMPTY {
            get {
                return ResourceManager.GetString("VALUE_MUST_BE_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Value must be equal to &apos;{0}&apos;..
        /// </summary>
        public static string VALUE_MUST_BE_EQUAL_TO {
            get {
                return ResourceManager.GetString("VALUE_MUST_BE_EQUAL_TO", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Value must be greater than &apos;{0}&apos;..
        /// </summary>
        public static string VALUE_MUST_BE_GREATER_THAN {
            get {
                return ResourceManager.GetString("VALUE_MUST_BE_GREATER_THAN", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Value must be greater than or equal to &apos;{0}&apos;..
        /// </summary>
        public static string VALUE_MUST_BE_GREATER_THAN_OR_EQUAL_TO {
            get {
                return ResourceManager.GetString("VALUE_MUST_BE_GREATER_THAN_OR_EQUAL_TO", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Value must be less than &apos;{0}&apos;..
        /// </summary>
        public static string VALUE_MUST_BE_LESS_THAN {
            get {
                return ResourceManager.GetString("VALUE_MUST_BE_LESS_THAN", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Value must be less than or equal to &apos;{0}&apos;..
        /// </summary>
        public static string VALUE_MUST_BE_LESS_THAN_OR_EQUAL_TO {
            get {
                return ResourceManager.GetString("VALUE_MUST_BE_LESS_THAN_OR_EQUAL_TO", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Value must be null..
        /// </summary>
        public static string VALUE_MUST_BE_NULL {
            get {
                return ResourceManager.GetString("VALUE_MUST_BE_NULL", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Value must be type &apos;{0}&apos;..
        /// </summary>
        public static string VALUE_MUST_BE_TYPE {
            get {
                return ResourceManager.GetString("VALUE_MUST_BE_TYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Value must contain &apos;{0}&apos;..
        /// </summary>
        public static string VALUE_MUST_CONTAIN {
            get {
                return ResourceManager.GetString("VALUE_MUST_CONTAIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Value must end with &apos;{0}&apos;..
        /// </summary>
        public static string VALUE_MUST_END_WITH {
            get {
                return ResourceManager.GetString("VALUE_MUST_END_WITH", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Value must have a length between {0} and {1}..
        /// </summary>
        public static string VALUE_MUST_HAVE_LENGTH_BETWEEN {
            get {
                return ResourceManager.GetString("VALUE_MUST_HAVE_LENGTH_BETWEEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Value must have a length equal to {0}..
        /// </summary>
        public static string VALUE_MUST_HAVE_LENGTH_EQUAL_TO {
            get {
                return ResourceManager.GetString("VALUE_MUST_HAVE_LENGTH_EQUAL_TO", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Value must have a length greater than or equal to {0}..
        /// </summary>
        public static string VALUE_MUST_HAVE_LENGTH_GREATER_THAN_OR_EQUAL_TO {
            get {
                return ResourceManager.GetString("VALUE_MUST_HAVE_LENGTH_GREATER_THAN_OR_EQUAL_TO", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Value must have a length less than or equal to {0}..
        /// </summary>
        public static string VALUE_MUST_HAVE_LENGTH_LESS_THAN_OR_EQUAL_TO {
            get {
                return ResourceManager.GetString("VALUE_MUST_HAVE_LENGTH_LESS_THAN_OR_EQUAL_TO", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Value must not be equal to &apos;{0}&apos;..
        /// </summary>
        public static string VALUE_MUST_NOT_BE_EQUAL_TO {
            get {
                return ResourceManager.GetString("VALUE_MUST_NOT_BE_EQUAL_TO", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Value must start with &apos;{0}&apos;..
        /// </summary>
        public static string VALUE_MUST_START_WITH {
            get {
                return ResourceManager.GetString("VALUE_MUST_START_WITH", resourceCulture);
            }
        }
    }
}
